name: Koboy Game Workflow

on:
  issues:
    types: [opened]

jobs:
  process-game:
    if: startsWith(github.event.issue.title, '[PLAY]')
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      issues: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Process game move
        run: |
          python .github/scripts/game_processor.py "${{ github.event.issue.title }}" "${{ github.event.issue.user.login }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md game_state.json
          git commit -m "update game state from issue #${{ github.event.issue.number }}" || echo "No changes to commit"
          git push

      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            Thanks for playing! The game has been updated.
            
            Visit README.md to see the current status of the game.
